SELECT
PKC.OBJECT_TYPE,
PKC.OWNER||'.'||PKC.NAME,
PKC.COLUMN_NAME,
PKC.COLUMN_POSITION 
FROM DBA_PART_KEY_COLUMNS PKC, DBA_TABLES T
WHERE 
T.OWNER=PKC.OWNER AND T.TABLE_NAME=PKC.NAME
AND T.owner='&&v_owner'
and T.TABLE_name='&&v_table_name'
order by 1 desc,2,4
;