SELECT OWNER||'.'||TABLE_NAME tabname
,TO_CHAR(STATS_UPDATE_TIME,'YYYYMMDD HH24:MI:SS') ana_date
FROM DBA_TAB_STATS_HISTORY
WHERE TABLE_NAME='&&v_table_name'
AND OWNER='&&v_owner'
ORDER BY 1,2 DESC
;