--set lines 200
--col tablespace_name for a20;
--set pages 80;
--set feedback off;
--col SUM_SPACE(M) for 999,999,999;
--col SUM_BLOCKS for 999,999,999;
--col USED_SPACE(M)  for 999,999,999.99;
--col FREE_SPACE(M) for 999,999,999.99;
set pagesize 0
set linesize 1000
SELECT D.TABLESPACE_NAME,
       SPACE "SUM_SPACE(M)",
       --BLOCKS SUM_BLOCKS,
       SPACE - NVL(FREE_SPACE, 0) "USED_SPACE(M)",
       ROUND((1 - NVL(FREE_SPACE, 0) / SPACE) * 100, 2) "USED_RATE(%)",
       NVL(FREE_SPACE,0) "FREE_SPACE(M)"
  FROM (SELECT TABLESPACE_NAME,
               ROUND(SUM(BYTES) / (1024 * 1024), 2) SPACE,
               SUM(BLOCKS) BLOCKS
          FROM DBA_DATA_FILES
         GROUP BY TABLESPACE_NAME) D,
       (SELECT TABLESPACE_NAME,SUM(FREE_SPACE) FREE_SPACE
       FROM
       (SELECT TABLESPACE_NAME,
               ROUND(SUM(BYTES) / (1024 * 1024), 2) FREE_SPACE
          FROM DBA_FREE_SPACE
         GROUP BY TABLESPACE_NAME
         UNION ALL
        SELECT TABLESPACE_NAME,
             ROUND(SUM(BYTES) / (1024 * 1024),2) FREE_SPACE
          FROM DBA_UNDO_EXTENTS
          WHERE STATUS = 'EXPIRED'
          GROUP BY TABLESPACE_NAME)
         GROUP BY TABLESPACE_NAME) F
 WHERE D.TABLESPACE_NAME = F.TABLESPACE_NAME(+)
UNION ALL --if have tempfile
SELECT D.TABLESPACE_NAME,
       SPACE "SUM_SPACE(M)",
      -- BLOCKS SUM_BLOCKS,
       USED_SPACE "USED_SPACE(M)",
       ROUND(NVL(USED_SPACE, 0) / SPACE * 100, 2) "USED_RATE(%)",
       NVL((SPACE-USED_SPACE), 0) "FREE_SPACE(M)"
  FROM (SELECT TABLESPACE_NAME,
               ROUND(SUM(BYTES) / (1024 * 1024), 2) SPACE,
               SUM(BLOCKS) BLOCKS
          FROM DBA_TEMP_FILES
         GROUP BY TABLESPACE_NAME) D,
       (SELECT TABLESPACE_NAME,
               ROUND(SUM(USED_BLOCKS * 8192) / (1024 * 1024), 2) USED_SPACE
          FROM V$SORT_SEGMENT,SYS.TS$
         WHERE TABLESPACE_NAME=NAME
         GROUP BY TABLESPACE_NAME) F
 WHERE D.TABLESPACE_NAME = F.TABLESPACE_NAME(+) ;
 